[package]
name = "commander-core"
version = "1.2.0"
authors = ["dimos <doubledimos@outlook.com>"]
edition = "2018"
description = "This crate is used by commander-rust only. Please don't use it!"
license = "MIT"

[dependencies]
lazy_static = "1.2.0"
