[package]
authors = ["dimos <doubledimos@outlook.com>"]
edition = "2018"
name = "example-test"
version = "0.1.0"
description = "Yes, it is!"

[dependencies.commander-rust]
path = "../"

[features]
default = ["cn"]
cn = []
en = []